# Site theme
remote_theme: alixedi/typewriter

# Site settings
title: "Test"
description: "Private Eye"
baseurl: ""
url: "https://refinedsoftwarellc.github.io/test"

# Links
links:
  - title: "git"
    url: https://github.com/RefinedSoftwareLLC/test
